# monochrome theme cas yaz
background #1a1a1a
foreground #e0e0e0

# jellyy effect
cursor       #ffffff
cursor_trail 3
cursor_trail_decay 0.1 0.4

# grayscale ansi prati
# Black/Dark Gray
color0 #1a1a1a
color8 #404040

# grayred
color1 #555555
color9 #666666

# grenay
color2 #777777
color10 #888888

# yegray
color3 #999999
color11 #aaaaaa

# Basd
color4 #444444
color12 #5a5a5a

# Mcas
color5 #bbbbbb
color13 #cccccc

# asd
color6 #909090
color14 #b0b0b0

# asd
color7 #c0c0c0
color15 #ffffff

# layout
window_padding_width 15
hide_window_decorations yes
confirm_os_window_close 0

# fonts
# BEGIN_KITTY_FONTS
font_family      family="CaskaydiaCove Nerd Font"
bold_font        auto
italic_font      auto
bold_italic_font auto
# END_KITTY_FONTS

